export { useSelectedData } from './useSelectedData';
export { useDailyNorma } from './useDailyNorma';
export { useTemplaitingItem } from './useTemplaitingItem';
export { useTemplate } from './useTemplate';
export { formatingDate } from './formatingDate';
export { useGetUserNorma } from './useGetUserNorma';
export { useGetConsumedByDate } from './useGetConsumedByDate';
export { transformFirstLetter } from './transformFirstLetter';
export { useTranslateCategory } from './useTranslateCategory';
